# TSV file format:
# N.B tab separated columns in the tsv!
#flowcell  sample  library lane  R1  R2
samples: samples.tsv

scattercount: 40

b37:
  contigfiles: 18
  fasta: "/references/b37/human_g1k_v37_decoy.fasta"
  fai: "/references/b37/human_g1k_v37_decoy.fasta.fai"
  dict: "/references/b37/human_g1k_v37_decoy.dict"
  dbsnp: "/references/b37/dbsnp_138.b37.vcf.gz"
  hapmap: "/references/b37/hapmap_3.3.b37.vcf.gz"
  omni: "/references/b37/1000G_omni2.5.b37.vcf.gz"
  v1000g: "/references/b37/1000G_phase1.indels.b37.vcf.gz"
  mills: "/references/b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"

hg38:
  contigfiles: 19
  fasta: "/references/hg38/Homo_sapiens_assembly38.fasta"
  fai: "/references/hg38/Homo_sapiens_assembly38.fasta.fai"
  dict: "/references/hg38/Homo_sapiens_assembly38.dict"
  dbsnp: "/references/hg38/dbsnp_146.hg38.vcf.gz"
  hapmap: "/references/hg38/hapmap_3.3.hg38.vcf.gz"
  omni: "/references/hg38/1000G_omni2.5.hg38.vcf.gz"
  v1000g: "/references/hg38/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  mills: "/references/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
